# Generated by Django 4.1.10 on 2023-11-04 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_customuser_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='group',
        ),
        migrations.DeleteModel(
            name='SellerGroup',
        ),
    ]
