name: Django CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: ${{ secrets.USER_DB }}
          POSTGRES_PASSWORD: ${{ secrets.PASSWORD_DB }}
          POSTGRES_DB: postgres
          HOST_DB: ${{ secrets.HOST_DB }}
        ports:
          - 5432:5432

        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build and run container
      run: |
        docker-compose up
        docker-compose exec web python manage.py migrate
        docker-compose exec web python manage.py test